# these should be passed with an environment variable, since they should be known at deployment time
spring.datasource.url=jdbc:postgresql://localhost:5432/java-spring-boot-ms-template-db
spring.datasource.username=local-dev-only
spring.datasource.password=local-dev-only

# This is fine here
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jackson.date-format=com.panopticode.openapi.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# Enable to debug application at runtime
#logging.level.root=TRACE
# This adds many API endpoints for observability - see https://www.baeldung.com/spring-boot-actuators#3-predefined-endpoints
#management.endpoints.web.exposure.include=*