plugins {
    id 'java-library'
}

group = 'com.panopticode'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':')
    implementation 'org.junit.jupiter:junit-jupiter-api:6.0.1'//bom
    implementation 'org.assertj:assertj-core:3.27.6'//bom
}