description: Complete recipe object
type: object
required:
  - name
  - servings
  - difficulty
  - prepTimeM
properties:
  id:
    type: string
    format: uuid
  name:
    type: string
  servings:
    type: integer
    format: int32
  textIntro:
    type: string
  picture:
    type: string
  thumbnail:
    type: string
  difficulty:
    $ref: ../schemas/Difficulty.yaml
  prepTimeM:
    type: integer
    format: int32
  cookTimeM:
    type: integer
    format: int32
  textOutro:
    type: string
  ingredients:
    type: array
    items:
      $ref: ../schemas/Ingredient.yaml
